# Keep all public classes and their public/protected members
-keep public class * {
    public protected *;
}

# Keep all Spigot plugin classes
-keep class com.lightlogin.LightLogin
-keep class com.lightlogin.commands.*
-keep class com.lightlogin.listeners.*
-keep class com.lightlogin.database.*
-keep class com.lightlogin.discord.*

# Keep all Spigot API classes
-keep class org.bukkit.** { *; }
-keep class org.spigotmc.** { *; }

# Keep JDA classes
-keep class net.dv8tion.jda.** { *; }
-keep class com.neovisionaries.ws.client.** { *; }

# Keep method and field names in Spigot API
-keepclassmembernames class * {
    @org.bukkit.event.EventHandler *;
    @org.bukkit.plugin.java.JavaPlugin *;
}

# Keep all plugin.yml entries
-keepclassmembers class * extends org.bukkit.plugin.java.JavaPlugin {
    public void onEnable();
    public void onDisable();
}

# Keep database-related classes
-keep class * extends java.sql.Driver
-keep class com.h2database.** { *; }


# General obfuscation options
-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontshrink
-verbose

# Keep attributes and annotations
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,Exceptions,SourceFile,LineNumberTable,LocalVariableTable,LocalVariableTypeTable,Deprecated,Synthetic

# Keep native methods
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

# Keep setters in GUI's
-keepclassmembers public class * extends org.bukkit.inventory.ItemStack {
   void setType(org.bukkit.Material);
   void setItemMeta(org.bukkit.inventory.meta.ItemMeta);
   void setAmount(int);
   void setData(org.bukkit.material.MaterialData);
   void setDurability(short);
}

# Keep constructors for serializable classes
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# Keep database model classes
-keep class com.lightlogin.data.** { *; }
